name: Telegram OTA Ripper (Web App Backend)

# Menerima pemicu API dari Cloudflare Web App
on:
  workflow_dispatch:
    inputs:
      chat_id:
        description: 'Telegram Chat ID'
        required: true
      url:
        description: 'OTA URL'
        required: true
      partitions:
        description: 'Partisi yang di-dump (kosongkan jika full)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  extract-ota:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download & Setup otaripper
        run: |
          # Mengunduh versi Linux otaripper
          wget https://github.com/syedinsaf/otaripper/releases/download/v3.3.0/otaripper-3.3.0-linux-x86_64.tar.gz
          tar -xvf otaripper-3.3.0-linux-x86_64.tar.gz
          chmod +x otaripper

      - name: Run Extraction Task
        env:
          # Secret Kredensial Userbot
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          
          # Input parameter dari Web App Cloudflare
          CHAT_ID: ${{ github.event.inputs.chat_id }}
          OTA_URL: ${{ github.event.inputs.url }}
          PARTITIONS: ${{ github.event.inputs.partitions }}
        run: |
          # Menjalankan skrip Userbot Modular
          python backend/main.py
